---
abstract: 'Build and make available libarchive'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  File::ShareDir: 1.03
  Test::More: 0
configure_requires:
  Alien::Base: 0.002
  File::ShareDir: 1.03
dynamic_config: 1
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-Libarchive
requires:
  Alien::Base: 0.002
  File::ShareDir: 1.03
  Text::ParseWords: 0
  perl: 5.006
resources:
  bugtracker: https://github.com/plicease/alien-libarchive/issues
  homepage: http://perl.wdlabs.com/Alien-Libarchive/
  repository: git://github.com/plicease/alien-libarchive.git
version: 0.07
